
# Project intro
name: 'ra_test'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory.
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    ra_test:
        # staging models are all materialized views, for efficient storage, 
        # since they only transform data
        staging:
            materialized: view
        # dim tables are output, so materialized as tables
        dim:
            materialized: table
        # fact tables are output, so materialized as tables
        fact:
            materialized: table
    
